In [1]:
def column_names():
    """Reads column names for dataframe into array"""
    f = open("kddcup.names.txt")
    s = f.read()
    arr = s.split("\n")[1:-1]
    cols = [a[0:a.index(":")] for a in arr]
    cols.append("target")
    return cols

cols = column_names()

In [2]:
import pandas as pd

kddcup = pd.read_csv('kddcup.csv', index_col=False, names=cols)
kddcup.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [3]:
kddcup.isna().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
target                         0
dtype: int64

In [4]:
import numpy as np
    
kddcup['target'] = np.where(kddcup['target'] != "normal.", "virus", "normal")
kddcup['target'].value_counts()

target
virus     396743
normal     97278
Name: count, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

def data_encoder(df):
    encoder = LabelEncoder()
    df['protocol_type'] = encoder.fit_transform(df['protocol_type'])
    df['service'] = encoder.fit_transform(df['service'])
    df['flag'] = encoder.fit_transform(df['flag'])
    df['target'] = encoder.fit_transform(df['target'])
    return df

kddcup = data_encoder(kddcup)
kddcup.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,target
0,0,1,22,9,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,0
1,0,1,22,9,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0
2,0,1,22,9,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,0
3,0,1,22,9,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,0
4,0,1,22,9,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,0

In [6]:
correlations = kddcup.corr()
correlations['target'] = correlations['target'].abs()
correlations.sort_values('target', ascending=False, inplace=True)
correlations['target'][1:]

logged_in                      0.795282
count                          0.752978
dst_host_count                 0.642110
protocol_type                  0.616601
srv_count                      0.566829
dst_host_same_src_port_rate    0.481458
srv_diff_host_rate             0.364687
same_srv_rate                  0.247405
dst_host_srv_serror_rate       0.227975
serror_rate                    0.227739
dst_host_serror_rate           0.227205
srv_serror_rate                0.227189
dst_host_srv_diff_host_rate    0.204958
flag                           0.155672
service                        0.131723
duration                       0.118014
dst_host_diff_srv_rate         0.115901
dst_host_same_srv_rate         0.109950
dst_host_srv_count             0.062566
num_access_files               0.054268
dst_bytes                      0.037709
is_guest_login                 0.032299
wrong_fragment                 0.023630
num_file_creations             0.018671
diff_srv_rate                  0.016522
num_shells                     0.014951
num_root                       0.011006
su_attempted                   0.008789
hot                            0.006327
root_shell                     0.005871
num_compromised                0.005046
dst_host_srv_rerror_rate       0.003404
rerror_rate                    0.003190
srv_rerror_rate                0.003162
land                           0.002542
urgent                         0.001498
num_failed_logins              0.001060
src_bytes                      0.000936
dst_host_rerror_rate           0.000860
num_outbound_cmds                   NaN
is_host_login                       NaN
Name: target, dtype: float64

In [7]:
X = kddcup.drop(['target'], axis=1)
Y = kddcup['target']

In [8]:
from sklearn.preprocessing import StandardScaler

def data_scaling(X):
    """Scales each row in X dataframe to mean and regularized standard deviation"""
    scaler = StandardScaler()
    X = scaler.fit_transform(X)
    cols.remove('target')
    X = pd.DataFrame(X, columns=cols)
    return X

X = data_scaling(X)
X.describe()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,...,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05,4.940210e+05
mean,2.171810e-17,-1.647699e-16,-3.256276e-17,-3.589958e-17,6.508237e-19,4.717573e-18,-7.493462e-18,3.106694e-18,2.277883e-18,-2.035173e-17,...,6.811715e-17,-1.348536e-16,3.352929e-16,5.488494e-17,1.988284e-16,2.807531e-17,3.129707e-17,-5.983263e-17,1.822594e-16,-5.845188e-17
std,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,...,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00
min,-6.779172e-02,-8.115496e-01,-1.729084e+00,-3.484214e+00,-3.061686e-03,-2.628733e-02,-6.673418e-03,-4.772019e-02,-2.571468e-03,-4.413591e-02,...,-3.590542e+00,-1.779188e+00,-1.834994e+00,-2.828667e-01,-1.250621e+00,-1.586293e-01,-4.644176e-01,-4.632024e-01,-2.520395e-01,-2.494640e-01
25%,-6.779172e-02,-8.115496e-01,-6.949824e-01,5.142739e-01,-3.016149e-03,-2.628733e-02,-6.673418e-03,-4.772019e-02,-2.571468e-03,-4.413591e-02,...,3.479668e-01,-1.345391e+00,-8.368938e-01,-2.828667e-01,-1.250621e+00,-1.586293e-01,-4.644176e-01,-4.632024e-01,-2.520395e-01,-2.494640e-01
50%,-6.779172e-02,-8.115496e-01,-6.949824e-01,5.142739e-01,-2.535486e-03,-2.628733e-02,-6.673418e-03,-4.772019e-02,-2.571468e-03,-4.413591e-02,...,3.479668e-01,6.255576e-01,5.993962e-01,-2.828667e-01,8.270476e-01,-1.586293e-01,-4.644176e-01,-4.632024e-01,-2.520395e-01,-2.494640e-01
75%,-6.779172e-02,9.257531e-01,1.373221e+00,5.142739e-01,-2.017381e-03,-2.628733e-02,-6.673418e-03,-4.772019e-02,-2.571468e-03,-4.413591e-02,...,3.479668e-01,6.255576e-01,5.993962e-01,8.323588e-02,8.270476e-01,-1.586293e-01,-4.644176e-01,-4.632024e-01,-2.520395e-01,-2.494640e-01
max,8.234740e+01,2.663056e+00,3.072103e+00,9.585503e-01,7.016400e+02,1.560110e+02,1.498483e+02,2.220663e+01,5.444371e+02,3.831404e+01,...,3.479668e-01,6.255576e-01,5.993962e-01,8.869697e+00,8.270476e-01,2.357583e+01,2.163063e+00,2.162027e+00,4.084676e+00,4.095715e+00

In [9]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

def feature_selection(X, Y):
    """Selects highest correlated features from X dataframe"""
    clf = ExtraTreesClassifier().fit(X, Y)
    model = SelectFromModel(clf, prefit=True)
    X_new = model.transform(X)
    return X_new

X_new = feature_selection(X, Y)
X_new.shape

c:\Users\ConnorMullikin\anaconda\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  warnings.warn(

(494021, 12)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_new, Y, test_size=0.3, random_state=1)

In [11]:
# !pip install bayesian-optimization

In [12]:
from bayes_opt import BayesianOptimization
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def RFC_cv(max_features, n_estimators, X, Y):
    """Creates RandomForestClassifier model with inputted parameters and runs cross validation
    to measure accuracy of model with given parameters"""
    estimator = RandomForestClassifier(
        max_features = max_features,                       
        n_estimators = n_estimators
    )
    cval = cross_val_score(estimator, X, Y, cv=4)
    return cval.mean()

def optimize_RFC(X, Y):
    """Uses Bayesian optimization function to narrow down most accurate values for parameters
    and returns parameters from model with highest accuracy"""
    def RFC_crossval(max_features, n_estimators):
        """Wrapper that converts parameters into correct format and returns model results
        from RFC_cv()"""
        return rfc_cv(
            max_features = 'log2' if max_features < 1 else 'sqrt',                     
            n_estimators = int(n_estimators),
            X = X,
            Y = Y
        )
    
    optimizer = BayesianOptimization(
       f=rfc_crossval,
        pbounds={
            # "max_depth": (10, 100),
            "max_features": (0, 2),
            # "min_samples_leaf": (1, 4),
            # "min_samples_split": (2, 10),
            "n_estimators": (10, 250),
        },
        random_state=1
    )
    optimizer.maximize(init_points = 3, n_iter=5)
    print(optimizer.max)
    return optimizer.max['params']

# rfc_params = optimize_RFC(X_train, Y_train)

In [13]:
# from sklearn.linear_model import LogisticRegression

# def LogReg_cv(solver, C, X, Y):
#     estimator = LogisticRegression(
#         solver = solver,
#         C = C
#     )
#     cval = cross_val_score(estimator, X, Y, cv=5)
#     return cval.mean()

# def optimize_LogReg(X, Y):
#     def LogReg_crossval(solver, C):
#         return logreg_cv(
#             solver = 'newton-cg' if solver < 1 else 'lbfgs' if solver < 2 else 'liblinear',
#             C = C,
#             X = X,
#             Y = Y
#         )
    
#     optimizer = BayesianOptimization(
#        f=logreg_crossval,
#         pbounds={
#             "solver": (0, 3),
#             "C": (0.01, 100)
#         },
#         random_state=1
#     )
#     optimizer.maximize(init_points = 3, n_iter=6)
#     print(optimizer.max)
#     return optimizer.max['params']

# logreg_params = optimize_LogReg(X_train, Y_train)

In [14]:
# import time
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import GaussianNB
# from sklearn.neighbors import KNeighborsClassifier 
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.svm import SVC  

# start = time.time()
# GBC = GradientBoostingClassifier(random_state=1)
# GBC.fit(X_train, Y_train)
# end = time.time()
# print(f"Gradient Boosting time to train: {end-start}")

# start = time.time()
# rfc_params = optimize_RFC(X, Y)
# rfc_params['max_features'] = rfc_params['max_features'][0]                     
# rfc_params['n_estimators'] = int(rfc_params.get('n_estimators'))
# RFC = RandomForestClassifier(#**rfc_params,
#                             random_state=1)
# RFC.fit(X_train, Y_train)
# end = time.time()
# print(f"Random Forest time to train: {end-start}")

# start = time.time()
# LogReg = LogisticRegression(random_state=1)
# LogReg.fit(X_train, Y_train)
# end = time.time()
# print(f"Logistic Regression time to train: {end-start}")

# start = time.time()
# NB = GaussianNB()
# NB.fit(X_train, Y_train)
# end = time.time()
# print(f"Gaussian Naive Bayes time to train: {end-start}")

# start = time.time()
# DTC = DecisionTreeClassifier(random_state=1)
# DTC.fit(X_train, Y_train)
# end = time.time()
# print(f"Decision Tree time to train: {end-start}")

# start = time.time()
# SVM = SVC(kernel='linear', random_state=1)
# SVM.fit(X_train, Y_train)
# end = time.time()
# print(f"Support Vector Machine time to train: {end-start}")

In [15]:
# from sklearn import metrics
# from sklearn.model_selection import cross_val_score

# models = []
# models.append(('Gradient Boosting', GBC))
# models.append(('Random Forest', RFC))
# models.append(('Logistic Regression', LogReg))
# models.append(('Naive Bayes', NB))
# models.append(('Decision Trees', DTC))
# models.append(('Support Vector Machine', SVM))

# for name, model in models:
#     print(f"Model: {name}")

#     start = time.time()
#     predictions = model.predict(X_test)
#     end = time.time()
#     print(f"Time to train: {end-start}")
    
#     accuracy = metrics.accuracy_score(Y_test, predictions)
#     confusion_matrix = metrics.confusion_matrix(Y_test, predictions)
#     classification = metrics.classification_report(Y_test, predictions)
#     print(f"Accuracy score: {accuracy}")
#     print(f"Confusion matrix: \n{confusion_matrix}")
#     print(f"Classification: \n{classification}")

#     scores = cross_val_score(model, X, Y, cv=5)
#     print(f"Cross validation mean score: {scores.mean()}")

In [16]:
import time

def train(name, model_type, X, Y):
    """Fits model off of training data and returns them"""
    print(f"Model: {name}")
    name = model_type(random_state=1) if name != "Naive Bayes" else model_type()
    
    start = time.time()
    name.fit(X, Y)
    end = time.time()
    print(f"Time to train: {end-start}")
    return name

In [17]:
from sklearn import metrics
from sklearn.model_selection import cross_val_score

def test(name, model, X, Y):
    """Runs model on testing data and returns variety of tests to show accuracy
    of model on testing data, including cross validation"""
    start = time.time()
    predictions = model.predict(X)
    end = time.time()
    print(f"Time to test: {end-start}")
    
    accuracy = metrics.accuracy_score(Y, predictions)
    confusion_matrix = metrics.confusion_matrix(Y, predictions)
    classification = metrics.classification_report(Y, predictions)
    print(f"Accuracy score: {accuracy}")
    print(f"Confusion matrix: \n{confusion_matrix}")
    print(f"Classification: \n{classification}")

    scores = cross_val_score(model, X, Y, cv=5)
    print(f"Cross validation mean score: {scores.mean()}")
    print(f"")
    return scores.mean()

In [18]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC  

models = []
models.append(('Gradient Boosting', GradientBoostingClassifier))
models.append(('Random Forest', RandomForestClassifier))
models.append(('Logistic Regression', LogisticRegression))
models.append(('Naive Bayes', GaussianNB))
models.append(('Decision Trees', DecisionTreeClassifier))
# models.append(('Support Vector Machine', SVC))

model_accuracy = {}
for name, model_type in models:
    model = train(name, model_type, X_train, Y_train)
    score = test(name, model, X_test, Y_test)
    model_accuracy[name] = score

max(model_accuracy, key=model_accuracy.get)

Model: Gradient Boosting
Time to train: 18.134488344192505
Time to test: 0.10697603225708008
Accuracy score: 0.9934078687241493
Confusion matrix:
[[ 28984    122]
 [   855 118246]]
Classification:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     29106
           1       1.00      0.99      1.00    119101

    accuracy                           0.99    148207
   macro avg       0.99      0.99      0.99    148207
weighted avg       0.99      0.99      0.99    148207

Cross validation mean score: 0.9931649633491337

Model: Random Forest
Time to train: 8.50197172164917
Time to test: 0.6646816730499268
Accuracy score: 0.9951891611057507
Confusion matrix:
[[ 28935    171]
 [   542 118559]]
Classification:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29106
           1       1.00      1.00      1.00    119101

    accuracy                           1.00    148207
   macro avg       0.99      0.99      0.99    148207
weighted avg       1.00      1.00      1.00    148207

Cross validation mean score: 0.9947573338318494

Model: Logistic Regression

c:\Users\ConnorMullikin\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Time to train: 1.120140790939331
Time to test: 0.0
Accuracy score: 0.9859588278556344
Confusion matrix:
[[ 28648    458]
 [  1623 117478]]
Classification:
              precision    recall  f1-score   support

           0       0.95      0.98      0.96     29106
           1       1.00      0.99      0.99    119101

    accuracy                           0.99    148207
   macro avg       0.97      0.99      0.98    148207
weighted avg       0.99      0.99      0.99    148207

c:\Users\ConnorMullikin\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ConnorMullikin\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ConnorMullikin\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Cross validation mean score: 0.9859655785858792

Model: Naive Bayes
Time to train: 0.07564210891723633
Time to test: 0.038245439529418945
Accuracy score: 0.9814178817464763
Confusion matrix:
[[ 28396    710]
 [  2044 117057]]
Classification:
              precision    recall  f1-score   support

           0       0.93      0.98      0.95     29106
           1       0.99      0.98      0.99    119101

    accuracy                           0.98    148207
   macro avg       0.96      0.98      0.97    148207
weighted avg       0.98      0.98      0.98    148207

Cross validation mean score: 0.9813301673146381

Model: Decision Trees
Time to train: 0.2601296901702881
Time to test: 0.008203268051147461
Accuracy score: 0.994757332649605
Confusion matrix:
[[ 28909    197]
 [   580 118521]]
Classification:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99     29106
           1       1.00      1.00      1.00    119101

    accuracy                           0.99    148207
   macro avg       0.99      0.99      0.99    148207
weighted avg       0.99      0.99      0.99    148207

Cross validation mean score: 0.9940691097791359

'Random Forest'

In [19]:
!pip install tensorflow
!pip install keras

Could not fetch URL https://pypi.org/simple/tensorflow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tensorflow/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/tensorflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/tensorflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/tensorflow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/tensorflow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/tensorflow/
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

Could not fetch URL https://pypi.org/simple/keras/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/keras/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/keras/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/keras/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/keras/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/keras/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/keras/
ERROR: Could not find a version that satisfies the requirement keras (from versions: none)
ERROR: No matching distribution found for keras

In [20]:
from keras.models import Sequential
from keras.layers import Dense

ANN = Sequential()
ANN.add(Dense(128, activation='relu', input_dim=2))
ANN.add(Dense(1, activation='sigmoid'))
ANN.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = ANN.fit(X_train, Y_train, epochs=40, batch_size=10, validation_split=0.2)
history

ModuleNotFoundError: No module named 'keras'